# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Saberfront Official Site
email: saberfront.game.series@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The official blog and website of the Saberfront game series
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SaberfrontDevs
github_username:  Saberfront

# Build settings
markdown: kramdown
lsi: true

collections:
   systems
